### ISSUE TITLE
winston problem: Cannot log to file without filename or stream.

### ISSUE THREAD

**Issue by micio86dev** [watscho/express-mongodb-rest-api-boilerplate#32]
npm run watch

> express-mongodb-rest-api-boilerplate@1.0.3 watch /Users/alessandromicelli/Desktop/Progetti/Personali/Server/portfolio
> npm run rm:public && cross-env ts-node-dev --files --respawn --inspect -r tsconfig-paths/register ./src

> express-mongodb-rest-api-boilerplate@1.0.3 rm:public
> rm -rf ./public

[INFO] 19:32:38 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 5.0.2)
Debugger listening on ws://127.0.0.1:9229/0e38ee98-4637-4016-948f-4e482c1e71bc
For help, see: https://nodejs.org/en/docs/inspector
Error: Cannot log to file without filename or stream.
    at new File (/Users/alessandromicelli/Desktop/Progetti/Personali/Server/portfolio/node_modules/.pnpm/winston@3.8.2/node_modules/winston/lib/winston/transports/file.js:73:13)
    at Object.<anonymous> (/Users/alessandromicelli/Desktop/Progetti/Personali/Server/portfolio/src/infrastructure/logger.ts:8:16)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._compile (/Users/alessandromicelli/Desktop/Progetti/Personali/Server/portfolio/node_modules/.pnpm/source-map-support@0.5.21/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/private/var/folders/j7/6x0f1gyj2d13pgxjmbvmpgn00000gn/T/ts-node-dev-hook-024141453726162165.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/j7/6x0f1gyj2d13pgxjmbvmpgn00000gn/T/ts-node-dev-hook-024141453726162165.js:114:20)
    at require.extensions.<computed> (/private/var/folders/j7/6x0f1gyj2d13pgxjmbvmpgn00000gn/T/ts-node-dev-hook-024141453726162165.js:71:20)
    at Object.nodeDevHook [as .ts] (/Users/alessandromicelli/Desktop/Progetti/Personali/Server/portfolio/node_modules/.pnpm/ts-node-dev@2.0.0_sxidjv3cojnrggmso45tj7hldi/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
[ERROR] 19:32:39 Error: Cannot log to file without filename or stream.

**Comment by watscho** [comment]
Did you copy .env.exampe to .env ?  in terminal:  cp .env.example .env

**Comment by micio86dev** [comment]
Node 19, i didn't copy de env file maybe it'is the problem

Il ven 17 mar 2023, 20:57 watscho ***@***.***> ha scritto:

**Comment by watscho** [comment]
Yes it is. try please
